name = "JCL"
version = 1
is_stable = true
config_path = null
port = 8000 + 80
timeout = 30 * 1000
half = 100 / 2
remainder = 10 % 3
is_production = version > 0.5
needs_update = version < 2 and !is_stable
status = if is_production then "live" else "dev"
effective_port = config_path ?? port
fallback_name = null ?? "default" ?? "backup"